os:
  - linux
dist: trusty
language: c
sudo: required
env:
  matrix:
    - OCAML_VERSION=4.07
  global:
    secure: rdOEbahAv+ShjeIjrsSXj2lpUptoYpDycW0ktIZ0P875/CKbfk/AYzy7/SRdpFw3X8AWKvAX4L0Kque80EeS55MDCJiqmljAPg4UQWevhJ4Blz2/fScql4k3Ooaxm73aF99x+9IY3Eq8WAH1mky9q3fQlyY/nxeI/v64sk1gTNrEY8509zz6beidjfDR1z1lfo85kJA/uDNTV5BmXY9O1MUpMV9seI+BmK3tKZvQQiNzaleO8Dh9CK8uI421w/mKjktxgMZO0DdWhxI9KighPASI3DHWgacr4aBF127+6WDP7fu84pNn8Elm22XbNnGTDsHbhCrFYpEwuFBQP8ahQ9n05a9oQR7oNdpi0aSIju/NK6kq9YPwbbbe3Qem8wz48Hjnlx15Ckw9xUu1U61RUaLtGWWuTPlbp2LmXMx1zgDzoxcOfcw9/wC5DDX04R4kDhMoOdIebYesf5wD01TRpfmrOBvufKss8ERFAhb3Hz0XeRd6ZdjIgxe4fq5BUgosIO3sJLmfCB9QVAzUSZHZ9o3HoG0szcG6M/8NO5cM1YDKX3FxallEPaFXb5ZQNVQn64pBoxdAc7HOaMGn5AbtZbFo/ChuwPPJOAt00At5xkUe+LO3HF+T6mT5eXBtCCRhFi60Q7Vzt2cJubwLBAkk481cGO30GR1cjYhCkUw7EoU=
cache:
    directories:
      - $HOME/.opam.cached
      - $HOME/local
before_install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
  - opam update
install:
  - git clone https://github.com/gfngfn/SATySFi.git
  - cd SATySFi
  - opam pin add -y satysfi .
  - opam install -y satysfi
before_script:
  - mkdir -p "$HOME/.satysfi"
  - cp -r ./lib-satysfi/dist "$HOME/.satysfi/dist"
  - wget https://jaist.dl.sourceforge.net/project/junicode/junicode/junicode-1.002/junicode-1.002.zip
  - unzip junicode-1.002.zip
  - cp -r *.ttf "$HOME/.satysfi/dist/fonts/"
script:
  - cd doc
  - make all
  - make lang
  - make math1
after_success:
  - cd ../../
  - cp ./SATySFi/doc/primitives.pdf ./
  - cp ./SATySFi/doc/lang.pdf ./
  - cp ./SATySFi/doc/math1.pdf ./
  - ./deploy.sh
